# Generated by Django 3.0.6 on 2020-06-27 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('useraccount', '0005_auto_20200627_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='ORMProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccount.ORMUser')),
            ],
            options={
                'verbose_name': 'ORMProject',
                'verbose_name_plural': 'ORMProjects',
            },
        ),
    ]
