# Generated by Django 3.0.6 on 2020-06-27 05:59

from django.db import migrations


class Migration(migrations.Migration):
    atomic=False

    dependencies = [
        ('useraccount', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='ORMDepartment',
        ),
        migrations.RenameModel(
            old_name='Role',
            new_name='ORMRole',
        ),
        migrations.RenameModel(
            old_name='Skill',
            new_name='ORMSkill',
        ),
    ]
