# Generated by Django 3.0.6 on 2020-06-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0003_auto_20200627_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ormskill',
            name='skill_name',
            field=models.CharField(choices=[('IOT', 'Internet Of Things'), ('ML', 'Machine Learning'), ('AI', 'Artificial Inteligence')], max_length=10),
        ),
    ]
