# Generated by Django 3.0.6 on 2020-06-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0004_auto_20200627_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ormuser',
            old_name='skill',
            new_name='skills',
        ),
        migrations.AlterField(
            model_name='ormskill',
            name='skill_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ormuser',
            name='login_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='ORMProject',
        ),
    ]
